---
baseURL: https://vienna-photoblog.netlify.app
languageCode: en-us
title: Vienna Photoblog
pygmentsstyle: monokai
module:
  imports:
  - path: github.com/markterpstra/vienna-photoblog
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
